all:
  children:
    production:
      hosts:
        hms-server:
          ansible_host: 172.31.199.196
          ansible_user: vamsi
          ansible_connection: local
          # Since you're already on the server, use local connection
          # ansible_ssh_private_key_file: ~/.ssh/id_rsa
          
    staging:
      hosts:
        hms-staging:
          ansible_host: staging-server-ip
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_host: localhost

